### ISSUE TITLE
HHH000346 during transaction

### ISSUE THREAD

**Issue by JOndik** [liuyangming/ByteJTA-sample#3]
Hibernate is logging following error on every transaction flush:

`ERROR [springcloud-demo-consumer,63551f617978738d,63551f617978738d,true] 18084 --- [nio-6080-exec-1] o.h.i.ExceptionMapperStandardImpl        : HHH000346: Error during managed flush [no transaction is in progress]`

**Comment by liuyangming** [comment]
It seems that hibernate requires the status of the current transaction in the beforeCompletion phase before the transaction commit/rollback, and at this time ByteJTA has already desociated the current transaction, which is why this problem occurs. Thinking about it carefully, it may not be rigorous to desociate the current transaction before beforeCompletion phase. This problem is scheduled to be fixed in the next version 0.5.0-ALPHA12, which will be released next week. Thanks for your feedback.

**Comment by liuyangming** [comment]
0.5.0-ALPHA12 has been released to fix this issue, please use the latest version.

**Comment by JOndik** [comment]
Seems okay. Thank you.
