### ISSUE TITLE
Flush is not being called automatically

### ISSUE THREAD

**Issue by JOndik** [liuyangming/ByteJTA-sample#4]
When EntityManager#persist (or JpaRepository#save) is called without EntityManager#flush, data is not persisted into DB automatically. It would be nice if flush was called automatically just like with standard transactions.

**Comment by liuyangming** [comment]
I made some adjustments about this. Please try again with version 0.5.0-BETA2. I think this version should fix this bug. Please let me know if there are other problems.

**Comment by JOndik** [comment]
Thank you,
Entities are being persisted without explicit flush call.
However, in case of entity state change (e.g. setter call), the change is not persisted to DB without explicit flush call.

**Comment by liuyangming** [comment]
I can't reproduce this phenomenon. The results of my test case show that after the property is modified, the managed object will take effect even if the save is not explicitly called. My test code is as follows:
```java
@ResponseBody
@RequestMapping(value = "/init", method = RequestMethod.POST)
@Transactional
public void init(@RequestParam String sourceAcctId, @RequestParam String targetAcctId, @RequestParam double amount) {
	Account account = this.accountDao.findById(targetAcctId);
	account.setAmount(account.getAmount() + 1.00);
}
```

By the way, the ByteJTA-sample is just a demo of the [ByteJTA ](https://github.com/liuyangming/ByteJTA) project, and it may be temporary and will be adjusted or replaced. I don't want to lose these valuable issues because of subsequent replacement of the ByteJTA-sample. so, I'll be very appreciate if you could post your issues [here](https://github.com/liuyangming/ByteJTA/issues).

**Comment by JOndik** [comment]
Looks like my problem is related to streaming directly from database along with Stream#map call - this will need explicit flush.
About issue posting - I am sorry. Next time, I will use ByteJTA project directly.
